services:
  mongodb:
    image: mongo:latest
    container_name: meu-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=senha_mongo
    volumes:
      - dados_mongo:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: meu-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      # Conecta o Mongo Express ao container do MongoDB usando as credenciais acima
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=senha_mongo
      # O "server" deve ser exatamente o nome do serviço do banco (mongodb)
      - ME_CONFIG_MONGODB_SERVER=mongodb
      # Usuário e senha para VOCÊ acessar a interface visual no navegador
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
    depends_on:
      - mongodb

volumes:
  dados_mongo:
